#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: "{branch} (#{build})"

# branches to build
branches:
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true
  - ps: $env:GIT_HASH=$env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

# clone directory
clone_folder: c:\projects\BitReader

# scripts that run after cloning repository
install:
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\arduino_ide_install.bat
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\arduino_library_install.bat
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\install_googletest.bat
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\install_rapidassist.bat
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\install_win32arduino.bat

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\arduino_build_sketch.bat Benchmark
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\arduino_build_sketch.bat ReadBits
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\arduino_build_sketch.bat WriteBits
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\build_library.bat

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
- cmd: call %APPVEYOR_BUILD_FOLDER%\ci\appveyor\test_script.bat
- ps: . "$env:APPVEYOR_BUILD_FOLDER\ci\appveyor\UploadJUnitFiles.ps1" -Path "$env:APPVEYOR_BUILD_FOLDER\build\bin"

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
- path: .\build\bin\Release\bitreader_unittest.release.xml
  name: bitreader_unittest.release.xml
